import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8fafc', padding: 15 },
    statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
    statBox: { width: '48%', padding: 15, borderRadius: 15, elevation: 3 },
    statLabel: { color: '#fff', fontSize: 12, opacity: 0.8, marginTop: 5 },
    statValue: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#1e293b', textAlign: 'left' },
    orderCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        borderLeftWidth: 4,
    },
    cancelledCard: { opacity: 0.6, backgroundColor: '#f1f5f9' },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    idSection: { flexDirection: 'row', alignItems: 'center' },
    orderNumber: { fontWeight: 'bold', fontSize: 16, marginHorizontal: 5, color: '#334155' },
    typeBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    typeText: { fontSize: 12, fontWeight: 'bold' },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    timeSection: { flexDirection: 'row', alignItems: 'center' },
    dateText: { fontSize: 12, color: '#64748b', marginHorizontal: 5 },
    priceSection: { alignItems: 'flex-end' },
    amountText: { fontSize: 18, fontWeight: 'bold', color: '#0f172a' },
    cancelledBadge: { backgroundColor: '#ef4444', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, borderRadius: 4, marginBottom: 4 },
    cancelledText: { color: '#fff', fontSize: 10, marginLeft: 3, fontWeight: 'bold' },
    strikeThrough: { textDecorationLine: 'line-through', color: '#94a3b8' },
    headerInfo: { marginBottom: 20, alignItems: 'flex-start' },
    barmanName: { fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
    welcomeText: { fontSize: 14, color: '#64748b' },
});